const s = "hthththththththththththththththththththththththththththcncncncncncncncncncncncncncncncncncncncncncncncnmnmnpmpmpmpmpmpmpmpmpmpmpmpmpmpmpmpmpmpmpmpmpmpmxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkxkeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaeaoioioioioioioioioioioioioioioioioioioioijbjbjbjbjbjbjbjbjbjbjbjbjbjbjbjbjbjbybzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyzyfzqfqfqfqfqfqfqfqfqfqfqfqfqfqfqfqfrqdrdrdrdrdrdrdrdrdrdrdrdrdrdrdrdrsgsgsgsgsgsgsgsgsgsgsgsgsgsgsgsgvwvwvwvwvwvwvwvwvwvwvwvwvwvwlwulululululululululululul"

for (let i = 0; i < s.length; i++) {
    if (s[i] === s[i + 1]) console.log("FOUND", i)
}